// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	errors "github.com/pkg/errors"
	v1alpha1 "github.com/stuttgart-things/xplane-provider-vspherevm/apis/namespaced/virtualmachine/v1alpha1"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this MachineSnapshot.
func (mg *MachineSnapshot) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.VirtualMachineUUID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.VirtualMachineUUIDRef,
		Selector:     mg.Spec.ForProvider.VirtualMachineUUIDSelector,
		To: reference.To{
			List:    &v1alpha1.VirtualMachineList{},
			Managed: &v1alpha1.VirtualMachine{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.VirtualMachineUUID")
	}
	mg.Spec.ForProvider.VirtualMachineUUID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.VirtualMachineUUIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.VirtualMachineUUID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.VirtualMachineUUIDRef,
		Selector:     mg.Spec.InitProvider.VirtualMachineUUIDSelector,
		To: reference.To{
			List:    &v1alpha1.VirtualMachineList{},
			Managed: &v1alpha1.VirtualMachine{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.VirtualMachineUUID")
	}
	mg.Spec.InitProvider.VirtualMachineUUID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.VirtualMachineUUIDRef = rsp.ResolvedReference

	return nil
}
