// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type MachineSnapshotInitParameters struct {
	Consolidate *bool `json:"consolidate,omitempty" tf:"consolidate,omitempty"`

	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	Memory *bool `json:"memory,omitempty" tf:"memory,omitempty"`

	Quiesce *bool `json:"quiesce,omitempty" tf:"quiesce,omitempty"`

	RemoveChildren *bool `json:"removeChildren,omitempty" tf:"remove_children,omitempty"`

	SnapshotName *string `json:"snapshotName,omitempty" tf:"snapshot_name,omitempty"`

	VirtualMachineUUID *string `json:"virtualMachineUuid,omitempty" tf:"virtual_machine_uuid,omitempty"`
}

type MachineSnapshotObservation struct {
	Consolidate *bool `json:"consolidate,omitempty" tf:"consolidate,omitempty"`

	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	Memory *bool `json:"memory,omitempty" tf:"memory,omitempty"`

	Quiesce *bool `json:"quiesce,omitempty" tf:"quiesce,omitempty"`

	RemoveChildren *bool `json:"removeChildren,omitempty" tf:"remove_children,omitempty"`

	SnapshotName *string `json:"snapshotName,omitempty" tf:"snapshot_name,omitempty"`

	VirtualMachineUUID *string `json:"virtualMachineUuid,omitempty" tf:"virtual_machine_uuid,omitempty"`
}

type MachineSnapshotParameters struct {

	// +kubebuilder:validation:Optional
	Consolidate *bool `json:"consolidate,omitempty" tf:"consolidate,omitempty"`

	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// +kubebuilder:validation:Optional
	Memory *bool `json:"memory,omitempty" tf:"memory,omitempty"`

	// +kubebuilder:validation:Optional
	Quiesce *bool `json:"quiesce,omitempty" tf:"quiesce,omitempty"`

	// +kubebuilder:validation:Optional
	RemoveChildren *bool `json:"removeChildren,omitempty" tf:"remove_children,omitempty"`

	// +kubebuilder:validation:Optional
	SnapshotName *string `json:"snapshotName,omitempty" tf:"snapshot_name,omitempty"`

	// +kubebuilder:validation:Optional
	VirtualMachineUUID *string `json:"virtualMachineUuid,omitempty" tf:"virtual_machine_uuid,omitempty"`
}

// MachineSnapshotSpec defines the desired state of MachineSnapshot
type MachineSnapshotSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            MachineSnapshotParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider MachineSnapshotInitParameters `json:"initProvider,omitempty"`
}

// MachineSnapshotStatus defines the observed state of MachineSnapshot.
type MachineSnapshotStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        MachineSnapshotObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// MachineSnapshot is the Schema for the MachineSnapshots API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,vspherevm}
type MachineSnapshot struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.description) || (has(self.initProvider) && has(self.initProvider.description))",message="spec.forProvider.description is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.memory) || (has(self.initProvider) && has(self.initProvider.memory))",message="spec.forProvider.memory is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.quiesce) || (has(self.initProvider) && has(self.initProvider.quiesce))",message="spec.forProvider.quiesce is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.snapshotName) || (has(self.initProvider) && has(self.initProvider.snapshotName))",message="spec.forProvider.snapshotName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.virtualMachineUuid) || (has(self.initProvider) && has(self.initProvider.virtualMachineUuid))",message="spec.forProvider.virtualMachineUuid is a required parameter"
	Spec   MachineSnapshotSpec   `json:"spec"`
	Status MachineSnapshotStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// MachineSnapshotList contains a list of MachineSnapshots
type MachineSnapshotList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []MachineSnapshot `json:"items"`
}

// Repository type metadata.
var (
	MachineSnapshot_Kind             = "MachineSnapshot"
	MachineSnapshot_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: MachineSnapshot_Kind}.String()
	MachineSnapshot_KindAPIVersion   = MachineSnapshot_Kind + "." + CRDGroupVersion.String()
	MachineSnapshot_GroupVersionKind = CRDGroupVersion.WithKind(MachineSnapshot_Kind)
)

func init() {
	SchemeBuilder.Register(&MachineSnapshot{}, &MachineSnapshotList{})
}
