---
name: Deploy Pages
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Release"]
    types: [completed]

jobs:
  pages:
    if: >-
      github.event_name == 'workflow_dispatch' ||
      github.event.workflow_run.conclusion == 'success'
    uses: stuttgart-things/github-workflow-templates/.github/workflows/call-deploy-pages.yaml@f7442f184bebda3b69a98cf8593989f1f8e78ad1 # main
    with:
      runs-on: ubuntu-latest
