---
name: Deploy Pages
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Release"]
    types: [completed]

jobs:
  pages:
    if: >-
      github.event_name == 'workflow_dispatch' ||
      github.event.workflow_run.conclusion == 'success'
    uses: stuttgart-things/github-workflow-templates/.github/workflows/call-deploy-pages.yaml@45b138dd6fe49d39816309fbda5f0a3b381de1ff # main
    with:
      runs-on: ubuntu-latest
